### ISSUE TITLE
UR3 and UR10 Support

### ISSUE THREAD

**Issue by danzeeeman** [CreativeInquiry/ofxRobotArm#3]
- [ ]  UR3/UR5/UR10 Inverse Kinematics update
- [ ]  UR3/UR10 Kinematic Model Tweaks
- [ ]  UR3/UR10 3D models

**Comment by harpreets** [comment]
I am trying to understand the joint position values in UR5KinematicModel.cpp#L53 to create similar models for UR3/UR10 - but haven't been able to get the gist of it.
 
-> Which .dae files are these coordinates from? I see _UR5.dae_ and a bunch of other _UR5_joint_x.dae_ files in the _bin_ folder. 
I tried to open these files in Fusion 360/Rhino and put in the points from the .cpp manually to understand where the joints were. But looks like C4D and Fusion/Rhino might have handedness difference or something because my manually plotted points in 3D space were way off from any joint.

-> I haven't gone through the user manual yet but how do I identify an exact joint position from a 3D model to pick up its coordinate from the CAD program? This would also he helpful to know to separate out the parts precisely from the single robot arm 3D model for different DAEs.

**Comment by danzeeeman** [comment]
Let me dig out the reference from UR I used. It's basically the distance in
meter between the center of each joint.

**Comment by harpreets** [comment]
I guess I saw a similar diagram in the service manual [here](https://s3-eu-west-1.amazonaws.com/ur-support-site/21987/UR3_User_Manual_en_US.pdf). Not sure if it says anything about the exact joint positions though.

<img src="http://i.imgur.com/iKzKnkX.png" /> 
Fig 11.1

-> Were all the parts e.g. ur5_joint0_0, ur5_joint0_0 removed from the main CAD (ur5.dae), placed separately at some orientation(?) at the origin in C4D?
-> Where exactly would these points lie for say ur5_joint0_0?

<img src="http://i.imgur.com/TpARxol.png" />
